import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import {
  ClerkProvider,
  SignedOut,
  SignedIn,
  SignInButton,
  SignUpButton,
  UserButton,
  SignOutButton,
} from '@clerk/nextjs';
import './globals.css';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} bg-gray-100 text-gray-900 min-h-screen overflow-hidden`}
        >
          <header className="bg-white shadow-md p-4 flex justify-between items-center">
            <h1 className="text-xl font-semibold">PDF-Reader</h1>
            <nav className="flex items-center gap-4">
              <SignedOut>
                <SignInButton>
                  <button className="px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700 transition">
                    Sign In
                  </button>
                </SignInButton>
                <SignUpButton>
                  <button className="px-4 py-2 bg-green-600 text-white rounded hover:bg-green-700 transition">
                    Sign Up
                  </button>
                </SignUpButton>
              </SignedOut>

              <SignedIn>
                <UserButton />
                <SignOutButton>
                  <button className="px-4 py-2 bg-red-600 text-white rounded hover:bg-red-700 transition">
                    Sign Out
                  </button>
                </SignOutButton>
              </SignedIn>
            </nav>
          </header>

          <main className="min-h-[calc(100vh-80px)] h-[calc(100vh-80px)] overflow-hidden flex flex-col">{children}</main>
        </body>
      </html>
    </ClerkProvider>
  );
}